@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 08 13:50:30 -0600 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim showGlitchInlab_behav -key {Behavioral:sim_1:Functional:showGlitchInlab} -tclbatch showGlitchInlab.tcl -protoinst "protoinst_files/prelabGlitch.protoinst" -protoinst "protoinst_files/prelabGlitchFixed.protoinst" -protoinst "protoinst_files/InlabGlitch.protoinst" -protoinst "protoinst_files/InlabGlitchOpositeChange.protoinst" -protoinst "protoinst_files/InlabGlitchFixed.protoinst" -log simulate.log"
call xsim  showGlitchInlab_behav -key {Behavioral:sim_1:Functional:showGlitchInlab} -tclbatch showGlitchInlab.tcl -protoinst "protoinst_files/prelabGlitch.protoinst" -protoinst "protoinst_files/prelabGlitchFixed.protoinst" -protoinst "protoinst_files/InlabGlitch.protoinst" -protoinst "protoinst_files/InlabGlitchOpositeChange.protoinst" -protoinst "protoinst_files/InlabGlitchFixed.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
